services:
  db:
    image: postgres:17.4
    container_name: "db"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "./src/main/resources/migrations/:/docker-entrypoint-initdb.d"
    networks:
      - my_network
    environment:
      POSTGRES_DB: "discord_clone"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
networks:
  my_network:
    driver: bridge